# Generated by Django 5.0.6 on 2024-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tasks_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='unknown-project', max_length=50),
        ),
    ]
